version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/edu-serverless
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: scripts/post-install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
      timeout: 60
